#!/bin/bash

echo "Creating bin directory if not presen yet..."
mkdir bin
cd bin
echo "Removing old .class files, if any..."
rm -rf *.class
cd ..

echo "Compiling into bin dir..."
javac -d bin Main.java

echo "Game will now start"
clear
cd bin
java Main
rm -rf *.class
cd ..

clear
