#!/bin/bash

echo "Removing bin dir if any and re-creating it..."
rm -rf bin
mkdir bin

echo "Compiling into bin dir..."
javac -d bin Main.java

echo "Game will now start"
clear
cd bin
java Main
cd ..

clear